services:
  mongo:
    image: mongo:latest
    container_name: examedge-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: examedge-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/examedge
    depends_on:
      - mongo
    ports:
      - "4000:4000"



volumes:
  mongo_data:

